services:
    sudoku.solver:
        class: Sudoku\Solver
        calls:
            - [addStrategy, ["@sudoku.strategy.single_cell"]]

    sudoku.strategy.single_cell:
        class: Sudoku\Strategy\SingleCell